### ISSUE TITLE
Tuya Binary Sensor Smoke Detector Release 2021.11 category ywbj no more supported

### ISSUE THREAD

**Issue by ArnolddeBolster** [tuya/tuya-device-sharing-sdk#12]
Tuya Binary Sensor Smoke Detector Release 2021.11 category ywbj no more supported.
I only receive battery_state and not the sensor_smoke_state.

Tuya ioT api does GET the value only by DP instruction instead of Standard Instruction Set.
It has worked before but since latest HAS CORE updates no more.

How can I solve this ?

**Comment by ArnolddeBolster** [comment]
solved by tuya, they added dp as public

**Comment by Sage222** [comment]
can you pls provide a link to the product? looking for one that is supported in HA - thank you

**Comment by ArnolddeBolster** [comment]
I bought mine at a local Action store and for as I know it isn't available anymore, but 'tuya'like devices are also available in aliexpress store

**Comment by Sage222** [comment]
yeah thank you - though i made that mistake before.. bought a Tuya device - and yes it works fine on the App - though no support on HA.. hence why im asking :)
